import java.io.IOException;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class subpath1Test {

	@BeforeEach
	void setUp() throws Exception {
	}

	@Test
	void testMain() throws IOException {
	   String[ ] ss= {"-map","subway.txt","-a","1号线","-o","lineno1.txt"};
		subpath1.main(ss);
		subpath1.l2.clear();
		String[] ss1= {"-map","subway.txt","-a","2号线","-o","lineno2.txt"};
		subpath1.main(ss1);
		subpath1.l3.clear();
		String[] ss2= {"-map","subway.txt","-a","3号线","-o","lineno3.txt"};
		subpath1.main(ss2);
		subpath1.l4.clear();
		String[] ss3= {"-map","subway.txt","-a","4号线","-o","lineno4.txt"};
		subpath1.main(ss3);
		subpath1.l10.clear();
		String[] ss4= {"-map","subway.txt","-a","10号线","-o","lineno10.txt"};
		subpath1.main(ss4);
		subpath1.ls1.clear();
		String[] ss5= {"-map","subway.txt","-a","s1号线","-o","linenos1.txt"};
		subpath1.main(ss5);
		subpath1.ls3.clear();
		String[] ss6= {"-map","subway.txt","-a","s3号线","-o","linenos3.txt"};
		subpath1.main(ss6);
		subpath1.ls7.clear();
		String[] ss7= {"-map","subway.txt","-a","s7号线","-o","linenos7.txt"};
		subpath1.main(ss7);
		subpath1.ls8.clear();	   	
		String[ ] ss8= {"-map","subway.txt","-a","s8号线","-o","linenos8.txt"};
		subpath1.main(ss8);
		subpath1.ls9.clear();
		String[ ] ss9= {"-map","subway.txt","-a","s9号线","-o","linenos9.txt"};
		subpath1.main(ss9);
		subpath1.l1.clear();
		subpath1.l10.clear();
		subpath1.l2.clear();
		subpath1.l3.clear();
		subpath1.l4.clear();
		subpath1.lineset.clear();
		subpath1.ls1.clear();
		subpath1.ls3.clear();
		subpath1.ls7.clear();
		subpath1.ls8.clear();
		subpath1.ls9.clear();
		subpath1.totalsat=0;
		String[ ] shortpath= {"-map","subway.txt","-b","孝陵卫","南京站","-o","path1.txt"};
		subpath1.main(shortpath);
		subpath1.l1.clear();
		subpath1.l10.clear();
		subpath1.l2.clear();
		subpath1.l3.clear();
		subpath1.l4.clear();
		subpath1.lineset.clear();
		subpath1.ls1.clear();
		subpath1.ls3.clear();
		subpath1.ls7.clear();
		subpath1.ls8.clear();
		subpath1.ls9.clear();
		subpath1.totalsat=0;
		String[ ] shortpath1= {"-map","subway.txt","-b","林场","南京站","-o","path2.txt"};
		subpath1.main(shortpath1);
		subpath1.l1.clear();
		subpath1.l10.clear();
		subpath1.l2.clear();
		subpath1.l3.clear();
		subpath1.l4.clear();
		subpath1.lineset.clear();
		subpath1.ls1.clear();
		subpath1.ls3.clear();
		subpath1.ls7.clear();
		subpath1.ls8.clear();
		subpath1.ls9.clear();
		subpath1.totalsat=0;
		String[ ] shortpath2= {"-map","subway.txt","-b","泰冯路","红山动物园","-o","path3.txt"};
		subpath1.main(shortpath2);
		subpath1.l1.clear();
		subpath1.l10.clear();
		subpath1.l2.clear();
		subpath1.l3.clear();
		subpath1.l4.clear();
		subpath1.lineset.clear();
		subpath1.ls1.clear();
		subpath1.ls3.clear();
		subpath1.ls7.clear();
		subpath1.ls8.clear();
		subpath1.ls9.clear();
		subpath1.totalsat=0;
		String[ ] shortpath3= {"-map","subway.txt","-b","铜山","奥体东","-o","path4.txt"};
		subpath1.main(shortpath3);
		subpath1.l1.clear();
		subpath1.l10.clear();
		subpath1.l2.clear();
		subpath1.l3.clear();
		subpath1.l4.clear();
		subpath1.lineset.clear();
		subpath1.ls1.clear();
		subpath1.ls3.clear();
		subpath1.ls7.clear();
		subpath1.ls8.clear();
		subpath1.ls9.clear();
		subpath1.totalsat=0;
		String[ ] shortpath4= {"-map","subway.txt","-b","鸡鸣寺","南京南站","-o","path5.txt"};
		subpath1.main(shortpath4);
		subpath1.l1.clear();
		subpath1.l10.clear();
		subpath1.l2.clear();
		subpath1.l3.clear();
		subpath1.l4.clear();
		subpath1.lineset.clear();
		subpath1.ls1.clear();
		subpath1.ls3.clear();
		subpath1.ls7.clear();
		subpath1.ls8.clear();
		subpath1.ls9.clear();
		subpath1.totalsat=0;
		String[ ] shortpath5= {"-map","subway.txt","-b","贾西","高淳","-o","path6.txt"};
		subpath1.main(shortpath5);
		subpath1.l1.clear();
		subpath1.l10.clear();
		subpath1.l2.clear();
		subpath1.l3.clear();
		subpath1.l4.clear();
		subpath1.lineset.clear();
		subpath1.ls1.clear();
		subpath1.ls3.clear();
		subpath1.ls7.clear();
		subpath1.ls8.clear();
		subpath1.ls9.clear();
		subpath1.totalsat=0;
		String[ ] shortpath6= {"-map","subway.txt","-b","绿博园","天隆寺","-o","path7.txt"};
		subpath1.main(shortpath6);
		subpath1.l1.clear();
		subpath1.l10.clear();
		subpath1.l2.clear();
		subpath1.l3.clear();
		subpath1.l4.clear();
		subpath1.lineset.clear();
		subpath1.ls1.clear();
		subpath1.ls3.clear();
		subpath1.ls7.clear();
		subpath1.ls8.clear();
		subpath1.ls9.clear();
		subpath1.totalsat=0;
		String[ ] shortpath7= {"-map","subway.txt","-b","安德门","信息工程大学","-o","path8.txt"};
		subpath1.main(shortpath7);
		subpath1.l1.clear();
		subpath1.l10.clear();
		subpath1.l2.clear();
		subpath1.l3.clear();
		subpath1.l4.clear();
		subpath1.lineset.clear();
		subpath1.ls1.clear();
		subpath1.ls3.clear();
		subpath1.ls7.clear();
		subpath1.ls8.clear();
		subpath1.ls9.clear();
		subpath1.totalsat=0;
		String[ ] shortpath8= {"-map","subway.txt","-b","雨花门","九华山","-o","path9.txt"};
		subpath1.main(shortpath8);
		subpath1.l1.clear();
		subpath1.l10.clear();
		subpath1.l2.clear();
		subpath1.l3.clear();
		subpath1.l4.clear();
		subpath1.lineset.clear();
		subpath1.ls1.clear();
		subpath1.ls3.clear();
		subpath1.ls7.clear();
		subpath1.ls8.clear();
		subpath1.ls9.clear();
		subpath1.totalsat=0;
		String[ ] shortpath9= {"-map","subway.txt","-b","云南路","明发广场","-o","path10.txt"};
		subpath1.main(shortpath9);
		subpath1.l1.clear();
		subpath1.l10.clear();
		subpath1.l2.clear();
		subpath1.l3.clear();
		subpath1.l4.clear();
		subpath1.lineset.clear();
		subpath1.ls1.clear();
		subpath1.ls3.clear();
		subpath1.ls7.clear();
		subpath1.ls8.clear();
		subpath1.ls9.clear();
		subpath1.totalsat=0;
		String[] shortpath10= {"-map","subway.txt","-b","林场","无想山","-o","path11.txt"};
		subpath1.main(shortpath10);
		subpath1.l1.clear();
		subpath1.l10.clear();
		subpath1.l2.clear();
		subpath1.l3.clear();
		subpath1.l4.clear();
		subpath1.lineset.clear();
		subpath1.ls1.clear();
		subpath1.ls3.clear();
		subpath1.ls7.clear();
		subpath1.ls8.clear();
		subpath1.ls9.clear();
		subpath1.totalsat=0;
		String[] shortpath11= {"-map","subway.txt","-b","仙林湖","高家冲","-o","path12.txt"};
		subpath1.main(shortpath11);
	}

}
